spring:
  application:
    name: '@app.name@'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
  jackson:
    mapper:
      accept-case-insensitive-properties: true
    deserialization:
      fail-on-unknown-properties: false
      fail-on-ignored-properties: false
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    root: info
    org:
      springframework: info
    com:
      amigoscode:
        chohort2:
          carRental: debug


cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  sso-profile: "SANDBOX-ADMIN"
  s3:
    buckets:
      org-name: rental-cars
      account: sandbox
      original-prefix: original
      s3domains:
        - name: cars
          media-type:
            - name: images
              resize-magnitude: 10
            - name: videos
              resize-magnitude: 2
        - name: brands
          media-type:
            - name: images
              resize-magnitude: 5
            - name: videos
              resize-magnitude: 3