spring:
  application:
    name: @app.name@
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
  jackson:
    mapper:
      accept-case-insensitive-properties: true
    deserialization:
      fail-on-unknown-properties: false
      fail-on-ignored-properties: false
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    root: info
    org:
      springframework: info
    com:
      amigoscode:
        chohort2:
          carRental: debug
