
name: Java CI with Maven

on:
  push:
    branches: ["main", "ci"]
  pull_request:
    branches: [ "main" ]
env:
  JAVA_VERSION: 17
  JAVA_DISTRO: temurin
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./carRental
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.JAVA_DISTRO}}
          cache: maven
      - name: Build with Maven
        run: mvn package -DskipTests

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6