version: "3.8"
services:
  temp-car-db:
    container_name: temp-car-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - car-db-network
    restart: unless-stopped

networks:
  car-db-network:
    driver: bridge

volumes:
  postgres_data: {}
