dbd:
	docker-compose down && docker-compose rm -fs
dbu:
	docker-compose up -d
dsp:
	docker system prune
dnp:
	docker network prune
mcp:
	mvn clean package
untrack-iml:
	git rm -r --cache *.iml
untrack-lock:
	git rm -r --cache *.lock.hcl
